import type { Exercise, MuscleGroup, Equipment, Category } from "./types";

type Row = [string, MuscleGroup, Equipment, Category, boolean?];

// id is auto-generated from a slug of the name. Order is roughly by muscle.
const ROWS: Row[] = [
  // --- CHEST -------------------------------------------------------------
  ["Barbell Bench Press", "Chest", "Barbell", "Strength", true],
  ["Incline Barbell Bench Press", "Chest", "Barbell", "Strength", true],
  ["Decline Barbell Bench Press", "Chest", "Barbell", "Strength", true],
  ["Close-Grip Barbell Bench Press", "Triceps", "Barbell", "Strength", true],
  ["Reverse-Grip Bench Press", "Chest", "Barbell", "Strength"],
  ["Pause Bench Press", "Chest", "Barbell", "Strength"],
  ["Spoto Press", "Chest", "Barbell", "Strength"],
  ["Floor Press", "Chest", "Barbell", "Strength"],
  ["Larsen Press", "Chest", "Barbell", "Strength"],
  ["Board Press", "Chest", "Barbell", "Strength"],
  ["Dumbbell Bench Press", "Chest", "Dumbbell", "Strength", true],
  ["Incline Dumbbell Bench Press", "Chest", "Dumbbell", "Strength", true],
  ["Decline Dumbbell Bench Press", "Chest", "Dumbbell", "Strength"],
  ["Dumbbell Floor Press", "Chest", "Dumbbell", "Strength"],
  ["Dumbbell Pullover", "Chest", "Dumbbell", "Strength"],
  ["Dumbbell Squeeze Press", "Chest", "Dumbbell", "Strength"],
  ["Dumbbell Hex Press", "Chest", "Dumbbell", "Strength"],
  ["Dumbbell Fly", "Chest", "Dumbbell", "Strength"],
  ["Incline Dumbbell Fly", "Chest", "Dumbbell", "Strength"],
  ["Decline Dumbbell Fly", "Chest", "Dumbbell", "Strength"],
  ["Cable Fly (High to Low)", "Chest", "Cable", "Strength"],
  ["Cable Fly (Low to High)", "Chest", "Cable", "Strength"],
  ["Standing Cable Fly", "Chest", "Cable", "Strength"],
  ["Cable Crossover", "Chest", "Cable", "Strength"],
  ["Single-Arm Cable Fly", "Chest", "Cable", "Strength"],
  ["Pec Deck", "Chest", "Machine", "Strength"],
  ["Machine Chest Press", "Chest", "Machine", "Strength"],
  ["Hammer Strength Chest Press", "Chest", "Machine", "Strength"],
  ["Smith Bench Press", "Chest", "Smith", "Strength"],
  ["Smith Incline Bench Press", "Chest", "Smith", "Strength"],
  ["Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Diamond Push-Up", "Triceps", "Bodyweight", "Strength"],
  ["Wide Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Decline Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Incline Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Archer Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Plyo Push-Up", "Chest", "Bodyweight", "Plyo"],
  ["Clap Push-Up", "Chest", "Bodyweight", "Plyo"],
  ["Spider-Man Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Ring Push-Up", "Chest", "Bodyweight", "Strength"],
  ["Chest Dip", "Chest", "Bodyweight", "Strength", true],
  ["Weighted Chest Dip", "Chest", "Bodyweight", "Strength", true],
  ["Svend Press", "Chest", "Other", "Strength"],
  ["Landmine Press", "Chest", "Barbell", "Strength"],
  ["Landmine Chest Press", "Chest", "Barbell", "Strength"],

  // --- BACK / LATS / TRAPS ----------------------------------------------
  ["Deadlift", "Back", "Barbell", "Strength", true],
  ["Sumo Deadlift", "Back", "Barbell", "Strength", true],
  ["Romanian Deadlift", "Hamstrings", "Barbell", "Strength", true],
  ["Stiff-Leg Deadlift", "Hamstrings", "Barbell", "Strength"],
  ["Trap Bar Deadlift", "Back", "Trap Bar", "Strength", true],
  ["Deficit Deadlift", "Back", "Barbell", "Strength"],
  ["Block Pull", "Back", "Barbell", "Strength"],
  ["Rack Pull", "Back", "Barbell", "Strength"],
  ["Snatch-Grip Deadlift", "Back", "Barbell", "Strength"],
  ["Pendlay Row", "Back", "Barbell", "Strength", true],
  ["Bent-Over Barbell Row", "Back", "Barbell", "Strength", true],
  ["Yates Row", "Back", "Barbell", "Strength"],
  ["T-Bar Row", "Back", "Barbell", "Strength", true],
  ["Meadows Row", "Back", "Barbell", "Strength"],
  ["Landmine Row", "Back", "Barbell", "Strength"],
  ["Chest-Supported T-Bar Row", "Back", "Machine", "Strength"],
  ["Dumbbell Row", "Back", "Dumbbell", "Strength", true],
  ["Single-Arm Dumbbell Row", "Back", "Dumbbell", "Strength", true],
  ["Chest-Supported Dumbbell Row", "Back", "Dumbbell", "Strength"],
  ["Kroc Row", "Back", "Dumbbell", "Strength"],
  ["Helms Row", "Back", "Dumbbell", "Strength"],
  ["Seal Row", "Back", "Barbell", "Strength"],
  ["Cable Row (Wide Grip)", "Back", "Cable", "Strength"],
  ["Cable Row (Close Grip)", "Back", "Cable", "Strength"],
  ["Single-Arm Cable Row", "Back", "Cable", "Strength"],
  ["Seated Cable Row", "Back", "Cable", "Strength", true],
  ["Lat Pulldown", "Lats", "Cable", "Strength", true],
  ["Wide-Grip Lat Pulldown", "Lats", "Cable", "Strength"],
  ["Reverse-Grip Lat Pulldown", "Lats", "Cable", "Strength"],
  ["Neutral-Grip Lat Pulldown", "Lats", "Cable", "Strength"],
  ["Single-Arm Lat Pulldown", "Lats", "Cable", "Strength"],
  ["Straight-Arm Pulldown", "Lats", "Cable", "Strength"],
  ["Cable Pullover", "Lats", "Cable", "Strength"],
  ["Pull-Up", "Lats", "Bodyweight", "Strength", true],
  ["Wide-Grip Pull-Up", "Lats", "Bodyweight", "Strength"],
  ["Chin-Up", "Lats", "Bodyweight", "Strength", true],
  ["Neutral-Grip Pull-Up", "Lats", "Bodyweight", "Strength"],
  ["Weighted Pull-Up", "Lats", "Bodyweight", "Strength", true],
  ["Weighted Chin-Up", "Lats", "Bodyweight", "Strength", true],
  ["L-Sit Pull-Up", "Lats", "Bodyweight", "Strength"],
  ["Muscle-Up", "Lats", "Bodyweight", "Strength"],
  ["Australian Row", "Back", "Bodyweight", "Strength"],
  ["Inverted Row", "Back", "Bodyweight", "Strength"],
  ["Ring Row", "Back", "Bodyweight", "Strength"],
  ["Machine Row", "Back", "Machine", "Strength"],
  ["Hammer Strength Row", "Back", "Machine", "Strength"],
  ["Hyperextension", "Back", "Bodyweight", "Strength"],
  ["Weighted Hyperextension", "Back", "Bodyweight", "Strength"],
  ["Reverse Hyperextension", "Back", "Machine", "Strength"],
  ["Good Morning", "Back", "Barbell", "Strength"],
  ["Seated Good Morning", "Back", "Barbell", "Strength"],
  ["Barbell Shrug", "Traps", "Barbell", "Strength"],
  ["Dumbbell Shrug", "Traps", "Dumbbell", "Strength"],
  ["Trap Bar Shrug", "Traps", "Trap Bar", "Strength"],
  ["Cable Shrug", "Traps", "Cable", "Strength"],
  ["Smith Shrug", "Traps", "Smith", "Strength"],
  ["Behind-the-Back Shrug", "Traps", "Barbell", "Strength"],
  ["Farmer Carry", "Traps", "Dumbbell", "Strength"],
  ["Suitcase Carry", "Obliques", "Dumbbell", "Strength"],
  ["Yoke Carry", "Traps", "Other", "Strength"],

  // --- SHOULDERS --------------------------------------------------------
  ["Overhead Press", "Shoulders", "Barbell", "Strength", true],
  ["Push Press", "Shoulders", "Barbell", "Strength", true],
  ["Push Jerk", "Shoulders", "Barbell", "Strength"],
  ["Behind-the-Neck Press", "Shoulders", "Barbell", "Strength"],
  ["Z Press", "Shoulders", "Barbell", "Strength"],
  ["Seated Barbell Overhead Press", "Shoulders", "Barbell", "Strength"],
  ["Dumbbell Shoulder Press", "Shoulders", "Dumbbell", "Strength", true],
  ["Seated Dumbbell Shoulder Press", "Shoulders", "Dumbbell", "Strength"],
  ["Arnold Press", "Shoulders", "Dumbbell", "Strength"],
  ["Single-Arm Dumbbell Press", "Shoulders", "Dumbbell", "Strength"],
  ["Dumbbell Cuban Press", "Shoulders", "Dumbbell", "Strength"],
  ["Bottoms-Up Kettlebell Press", "Shoulders", "Kettlebell", "Strength"],
  ["Kettlebell Strict Press", "Shoulders", "Kettlebell", "Strength"],
  ["Landmine Shoulder Press", "Shoulders", "Barbell", "Strength"],
  ["Half-Kneeling Landmine Press", "Shoulders", "Barbell", "Strength"],
  ["Machine Shoulder Press", "Shoulders", "Machine", "Strength"],
  ["Smith Overhead Press", "Shoulders", "Smith", "Strength"],
  ["Cable Lateral Raise", "Shoulders", "Cable", "Strength"],
  ["Dumbbell Lateral Raise", "Shoulders", "Dumbbell", "Strength"],
  ["Leaning Dumbbell Lateral Raise", "Shoulders", "Dumbbell", "Strength"],
  ["Seated Lateral Raise", "Shoulders", "Dumbbell", "Strength"],
  ["Machine Lateral Raise", "Shoulders", "Machine", "Strength"],
  ["Dumbbell Front Raise", "Shoulders", "Dumbbell", "Strength"],
  ["Plate Front Raise", "Shoulders", "Other", "Strength"],
  ["Cable Front Raise", "Shoulders", "Cable", "Strength"],
  ["Dumbbell Rear Delt Fly", "Shoulders", "Dumbbell", "Strength"],
  ["Cable Rear Delt Fly", "Shoulders", "Cable", "Strength"],
  ["Reverse Pec Deck", "Shoulders", "Machine", "Strength"],
  ["Face Pull", "Shoulders", "Cable", "Strength"],
  ["Band Pull-Apart", "Shoulders", "Band", "Strength"],
  ["Upright Row", "Shoulders", "Barbell", "Strength"],
  ["Dumbbell Upright Row", "Shoulders", "Dumbbell", "Strength"],
  ["Cable Upright Row", "Shoulders", "Cable", "Strength"],
  ["High Cable Row", "Shoulders", "Cable", "Strength"],
  ["Handstand Push-Up", "Shoulders", "Bodyweight", "Strength"],
  ["Pike Push-Up", "Shoulders", "Bodyweight", "Strength"],

  // --- BICEPS -----------------------------------------------------------
  ["Barbell Curl", "Biceps", "Barbell", "Strength"],
  ["EZ-Bar Curl", "Biceps", "EZ Bar", "Strength"],
  ["Reverse Curl", "Forearms", "EZ Bar", "Strength"],
  ["Wide-Grip Barbell Curl", "Biceps", "Barbell", "Strength"],
  ["Close-Grip Barbell Curl", "Biceps", "Barbell", "Strength"],
  ["Dumbbell Curl", "Biceps", "Dumbbell", "Strength"],
  ["Alternating Dumbbell Curl", "Biceps", "Dumbbell", "Strength"],
  ["Hammer Curl", "Biceps", "Dumbbell", "Strength"],
  ["Cross-Body Hammer Curl", "Biceps", "Dumbbell", "Strength"],
  ["Incline Dumbbell Curl", "Biceps", "Dumbbell", "Strength"],
  ["Spider Curl", "Biceps", "Dumbbell", "Strength"],
  ["Concentration Curl", "Biceps", "Dumbbell", "Strength"],
  ["Preacher Curl (Barbell)", "Biceps", "Barbell", "Strength"],
  ["Preacher Curl (Dumbbell)", "Biceps", "Dumbbell", "Strength"],
  ["Preacher Curl (Machine)", "Biceps", "Machine", "Strength"],
  ["Cable Curl", "Biceps", "Cable", "Strength"],
  ["Bayesian Cable Curl", "Biceps", "Cable", "Strength"],
  ["Cable Hammer Curl", "Biceps", "Cable", "Strength"],
  ["Rope Hammer Curl", "Biceps", "Cable", "Strength"],
  ["Cable Drag Curl", "Biceps", "Cable", "Strength"],
  ["High Cable Curl", "Biceps", "Cable", "Strength"],
  ["Zottman Curl", "Biceps", "Dumbbell", "Strength"],
  ["Drag Curl", "Biceps", "Barbell", "Strength"],
  ["Chin-Up Curl", "Biceps", "Bodyweight", "Strength"],

  // --- TRICEPS ----------------------------------------------------------
  ["Tricep Dip", "Triceps", "Bodyweight", "Strength"],
  ["Bench Dip", "Triceps", "Bodyweight", "Strength"],
  ["Weighted Dip", "Triceps", "Bodyweight", "Strength"],
  ["Skull Crusher (EZ Bar)", "Triceps", "EZ Bar", "Strength"],
  ["Skull Crusher (Barbell)", "Triceps", "Barbell", "Strength"],
  ["Skull Crusher (Dumbbell)", "Triceps", "Dumbbell", "Strength"],
  ["JM Press", "Triceps", "Barbell", "Strength"],
  ["Tate Press", "Triceps", "Dumbbell", "Strength"],
  ["Tricep Pushdown (Rope)", "Triceps", "Cable", "Strength"],
  ["Tricep Pushdown (Bar)", "Triceps", "Cable", "Strength"],
  ["Tricep Pushdown (V-Bar)", "Triceps", "Cable", "Strength"],
  ["Reverse-Grip Pushdown", "Triceps", "Cable", "Strength"],
  ["Single-Arm Cable Pushdown", "Triceps", "Cable", "Strength"],
  ["Cable Overhead Tricep Extension", "Triceps", "Cable", "Strength"],
  ["Rope Overhead Extension", "Triceps", "Cable", "Strength"],
  ["Dumbbell Overhead Extension", "Triceps", "Dumbbell", "Strength"],
  ["Single-Arm Dumbbell Extension", "Triceps", "Dumbbell", "Strength"],
  ["Tricep Kickback", "Triceps", "Dumbbell", "Strength"],
  ["Cable Kickback", "Triceps", "Cable", "Strength"],
  ["Diamond Push-Up", "Triceps", "Bodyweight", "Strength"],
  ["Smith Close-Grip Bench", "Triceps", "Smith", "Strength"],

  // --- FOREARMS ---------------------------------------------------------
  ["Wrist Curl", "Forearms", "Barbell", "Strength"],
  ["Reverse Wrist Curl", "Forearms", "Barbell", "Strength"],
  ["Dumbbell Wrist Curl", "Forearms", "Dumbbell", "Strength"],
  ["Behind-the-Back Wrist Curl", "Forearms", "Barbell", "Strength"],
  ["Plate Pinch", "Forearms", "Other", "Strength"],
  ["Dead Hang", "Forearms", "Bodyweight", "Strength"],
  ["Towel Pull-Up", "Forearms", "Bodyweight", "Strength"],
  ["Wrist Roller", "Forearms", "Other", "Strength"],
  ["Captains of Crush", "Forearms", "Other", "Strength"],

  // --- QUADS ------------------------------------------------------------
  ["Back Squat", "Quads", "Barbell", "Strength", true],
  ["High-Bar Squat", "Quads", "Barbell", "Strength", true],
  ["Low-Bar Squat", "Quads", "Barbell", "Strength", true],
  ["Front Squat", "Quads", "Barbell", "Strength", true],
  ["Box Squat", "Quads", "Barbell", "Strength"],
  ["Pause Squat", "Quads", "Barbell", "Strength"],
  ["Tempo Squat", "Quads", "Barbell", "Strength"],
  ["Safety Bar Squat", "Quads", "Barbell", "Strength"],
  ["Zercher Squat", "Quads", "Barbell", "Strength"],
  ["Overhead Squat", "Quads", "Barbell", "Strength"],
  ["Goblet Squat", "Quads", "Dumbbell", "Strength"],
  ["Heels-Elevated Goblet Squat", "Quads", "Dumbbell", "Strength"],
  ["Dumbbell Squat", "Quads", "Dumbbell", "Strength"],
  ["Hack Squat", "Quads", "Machine", "Strength", true],
  ["Reverse Hack Squat", "Quads", "Machine", "Strength"],
  ["Smith Squat", "Quads", "Smith", "Strength"],
  ["Smith Front Squat", "Quads", "Smith", "Strength"],
  ["Belt Squat", "Quads", "Machine", "Strength"],
  ["Sissy Squat", "Quads", "Bodyweight", "Strength"],
  ["Spanish Squat", "Quads", "Band", "Strength"],
  ["Wall Sit", "Quads", "Bodyweight", "Strength"],
  ["Bulgarian Split Squat", "Quads", "Dumbbell", "Strength"],
  ["Barbell Bulgarian Split Squat", "Quads", "Barbell", "Strength"],
  ["Smith Bulgarian Split Squat", "Quads", "Smith", "Strength"],
  ["Walking Lunge", "Quads", "Dumbbell", "Strength"],
  ["Reverse Lunge", "Quads", "Dumbbell", "Strength"],
  ["Forward Lunge", "Quads", "Dumbbell", "Strength"],
  ["Curtsy Lunge", "Glutes", "Dumbbell", "Strength"],
  ["Step-Up", "Quads", "Dumbbell", "Strength"],
  ["Lateral Lunge", "Quads", "Dumbbell", "Strength"],
  ["Pistol Squat", "Quads", "Bodyweight", "Strength"],
  ["Cossack Squat", "Quads", "Dumbbell", "Strength"],
  ["Leg Press", "Quads", "Machine", "Strength", true],
  ["Single-Leg Press", "Quads", "Machine", "Strength"],
  ["Leg Extension", "Quads", "Machine", "Strength"],
  ["Single-Leg Extension", "Quads", "Machine", "Strength"],
  ["Sled Push", "Quads", "Other", "Strength"],
  ["Sled Drag", "Quads", "Other", "Strength"],

  // --- HAMSTRINGS / GLUTES ---------------------------------------------
  ["Lying Leg Curl", "Hamstrings", "Machine", "Strength"],
  ["Seated Leg Curl", "Hamstrings", "Machine", "Strength"],
  ["Standing Leg Curl", "Hamstrings", "Machine", "Strength"],
  ["Nordic Curl", "Hamstrings", "Bodyweight", "Strength"],
  ["Razor Curl", "Hamstrings", "Bodyweight", "Strength"],
  ["Glute Ham Raise", "Hamstrings", "Machine", "Strength"],
  ["Single-Leg Romanian Deadlift", "Hamstrings", "Dumbbell", "Strength"],
  ["Dumbbell Romanian Deadlift", "Hamstrings", "Dumbbell", "Strength"],
  ["Cable Pull-Through", "Glutes", "Cable", "Strength"],
  ["Hip Thrust", "Glutes", "Barbell", "Strength", true],
  ["Single-Leg Hip Thrust", "Glutes", "Barbell", "Strength"],
  ["Smith Hip Thrust", "Glutes", "Smith", "Strength"],
  ["Machine Hip Thrust", "Glutes", "Machine", "Strength"],
  ["Glute Bridge", "Glutes", "Bodyweight", "Strength"],
  ["B-Stance Hip Thrust", "Glutes", "Barbell", "Strength"],
  ["Cable Kickback", "Glutes", "Cable", "Strength"],
  ["Cable Glute Kickback", "Glutes", "Cable", "Strength"],
  ["Machine Glute Kickback", "Glutes", "Machine", "Strength"],
  ["Hip Abduction Machine", "Glutes", "Machine", "Strength"],
  ["Standing Cable Hip Abduction", "Glutes", "Cable", "Strength"],
  ["Banded Side Walk", "Glutes", "Band", "Strength"],
  ["Banded Clamshell", "Glutes", "Band", "Strength"],
  ["Frog Pump", "Glutes", "Bodyweight", "Strength"],
  ["Kettlebell Swing", "Glutes", "Kettlebell", "Strength"],
  ["American Kettlebell Swing", "Glutes", "Kettlebell", "Strength"],

  // --- CALVES -----------------------------------------------------------
  ["Standing Calf Raise (Machine)", "Calves", "Machine", "Strength"],
  ["Seated Calf Raise (Machine)", "Calves", "Machine", "Strength"],
  ["Smith Calf Raise", "Calves", "Smith", "Strength"],
  ["Leg Press Calf Raise", "Calves", "Machine", "Strength"],
  ["Donkey Calf Raise", "Calves", "Machine", "Strength"],
  ["Single-Leg Calf Raise", "Calves", "Bodyweight", "Strength"],
  ["Dumbbell Calf Raise", "Calves", "Dumbbell", "Strength"],
  ["Tibialis Raise", "Calves", "Bodyweight", "Strength"],

  // --- ABS / OBLIQUES ---------------------------------------------------
  ["Crunch", "Abs", "Bodyweight", "Strength"],
  ["Sit-Up", "Abs", "Bodyweight", "Strength"],
  ["Decline Sit-Up", "Abs", "Bodyweight", "Strength"],
  ["Weighted Sit-Up", "Abs", "Bodyweight", "Strength"],
  ["Cable Crunch", "Abs", "Cable", "Strength"],
  ["Kneeling Cable Crunch", "Abs", "Cable", "Strength"],
  ["Machine Crunch", "Abs", "Machine", "Strength"],
  ["Hanging Leg Raise", "Abs", "Bodyweight", "Strength"],
  ["Hanging Knee Raise", "Abs", "Bodyweight", "Strength"],
  ["Toes-to-Bar", "Abs", "Bodyweight", "Strength"],
  ["Captain's Chair Knee Raise", "Abs", "Machine", "Strength"],
  ["Decline Leg Raise", "Abs", "Bodyweight", "Strength"],
  ["Lying Leg Raise", "Abs", "Bodyweight", "Strength"],
  ["Bicycle Crunch", "Obliques", "Bodyweight", "Strength"],
  ["Russian Twist", "Obliques", "Bodyweight", "Strength"],
  ["Weighted Russian Twist", "Obliques", "Other", "Strength"],
  ["Cable Woodchop", "Obliques", "Cable", "Strength"],
  ["Pallof Press", "Obliques", "Cable", "Strength"],
  ["Side Plank", "Obliques", "Bodyweight", "Strength"],
  ["Side Plank Reach-Through", "Obliques", "Bodyweight", "Strength"],
  ["Plank", "Abs", "Bodyweight", "Strength"],
  ["RKC Plank", "Abs", "Bodyweight", "Strength"],
  ["Long Lever Plank", "Abs", "Bodyweight", "Strength"],
  ["Weighted Plank", "Abs", "Bodyweight", "Strength"],
  ["Ab Wheel Rollout", "Abs", "Other", "Strength"],
  ["Standing Ab Wheel Rollout", "Abs", "Other", "Strength"],
  ["Dragon Flag", "Abs", "Bodyweight", "Strength"],
  ["L-Sit", "Abs", "Bodyweight", "Strength"],
  ["Hollow Hold", "Abs", "Bodyweight", "Strength"],
  ["Dead Bug", "Abs", "Bodyweight", "Strength"],
  ["Bird Dog", "Abs", "Bodyweight", "Strength"],
  ["Mountain Climber", "Abs", "Bodyweight", "Cardio"],
  ["Side Bend (Dumbbell)", "Obliques", "Dumbbell", "Strength"],
  ["Side Bend (Cable)", "Obliques", "Cable", "Strength"],

  // --- CARDIO / CONDITIONING -------------------------------------------
  ["Running", "Cardio", "Other", "Cardio"],
  ["Treadmill Sprint", "Cardio", "Machine", "Cardio"],
  ["Incline Treadmill Walk", "Cardio", "Machine", "Cardio"],
  ["Stair Climber", "Cardio", "Machine", "Cardio"],
  ["Rowing Erg", "Cardio", "Machine", "Cardio"],
  ["Assault Bike", "Cardio", "Machine", "Cardio"],
  ["Echo Bike", "Cardio", "Machine", "Cardio"],
  ["Stationary Bike", "Cardio", "Machine", "Cardio"],
  ["SkiErg", "Cardio", "Machine", "Cardio"],
  ["Jump Rope", "Cardio", "Other", "Cardio"],
  ["Burpee", "Full Body", "Bodyweight", "Cardio"],
  ["Burpee Pull-Up", "Full Body", "Bodyweight", "Cardio"],
  ["Box Jump", "Quads", "Other", "Plyo"],
  ["Broad Jump", "Quads", "Bodyweight", "Plyo"],
  ["Tuck Jump", "Quads", "Bodyweight", "Plyo"],
  ["Depth Jump", "Quads", "Other", "Plyo"],
  ["Clean", "Full Body", "Barbell", "Strength", true],
  ["Power Clean", "Full Body", "Barbell", "Strength", true],
  ["Hang Clean", "Full Body", "Barbell", "Strength"],
  ["Squat Clean", "Full Body", "Barbell", "Strength"],
  ["Snatch", "Full Body", "Barbell", "Strength", true],
  ["Power Snatch", "Full Body", "Barbell", "Strength"],
  ["Hang Snatch", "Full Body", "Barbell", "Strength"],
  ["Clean and Jerk", "Full Body", "Barbell", "Strength", true],
  ["Thruster", "Full Body", "Barbell", "Strength"],
  ["Wall Ball", "Full Body", "Other", "Strength"],
  ["Turkish Get-Up", "Full Body", "Kettlebell", "Strength"],
  ["Devil Press", "Full Body", "Dumbbell", "Cardio"],
  ["Man Maker", "Full Body", "Dumbbell", "Cardio"],

  // --- MOBILITY ---------------------------------------------------------
  ["World's Greatest Stretch", "Full Body", "Bodyweight", "Mobility"],
  ["Couch Stretch", "Quads", "Bodyweight", "Mobility"],
  ["Pigeon Pose", "Glutes", "Bodyweight", "Mobility"],
  ["Cat-Cow", "Back", "Bodyweight", "Mobility"],
  ["Thoracic Bridge", "Back", "Bodyweight", "Mobility"],
  ["90/90 Hip Stretch", "Glutes", "Bodyweight", "Mobility"],
  ["Cossack Stretch", "Quads", "Bodyweight", "Mobility"],
  ["Banded Shoulder Dislocate", "Shoulders", "Band", "Mobility"],
  ["Wall Slide", "Shoulders", "Bodyweight", "Mobility"],
  ["Scapular Pull-Up", "Lats", "Bodyweight", "Mobility"],
  ["Hip Flexor Stretch", "Quads", "Bodyweight", "Mobility"],
];

// Programmatic variant generation to push past 500 with realistic gym lifts.
const VARIANT_AMPLIFIERS: Array<{
  base: string;
  prefixes: string[];
  muscle: MuscleGroup;
  equipment: Equipment;
}> = [
  {
    base: "Bench Press",
    prefixes: ["Paused", "Tempo", "Banded", "Chained", "1.5-Rep"],
    muscle: "Chest",
    equipment: "Barbell",
  },
  {
    base: "Squat",
    prefixes: ["Paused", "Tempo", "Banded", "Chained", "1.5-Rep", "Pin"],
    muscle: "Quads",
    equipment: "Barbell",
  },
  {
    base: "Deadlift",
    prefixes: ["Paused", "Tempo", "Banded", "Chained", "Pin"],
    muscle: "Back",
    equipment: "Barbell",
  },
  {
    base: "Overhead Press",
    prefixes: ["Paused", "Tempo", "Banded", "1.5-Rep"],
    muscle: "Shoulders",
    equipment: "Barbell",
  },
  {
    base: "Bent-Over Row",
    prefixes: ["Paused", "Tempo", "Banded"],
    muscle: "Back",
    equipment: "Barbell",
  },
  {
    base: "Pull-Up",
    prefixes: ["Tempo", "1.5-Rep", "Eccentric", "Pause"],
    muscle: "Lats",
    equipment: "Bodyweight",
  },
  {
    base: "Dumbbell Curl",
    prefixes: ["Tempo", "21s", "Eccentric", "Pause"],
    muscle: "Biceps",
    equipment: "Dumbbell",
  },
  {
    base: "Tricep Pushdown",
    prefixes: ["Tempo", "21s", "Eccentric", "Pause"],
    muscle: "Triceps",
    equipment: "Cable",
  },
  {
    base: "Lateral Raise",
    prefixes: ["Tempo", "21s", "Drop-Set", "Pause"],
    muscle: "Shoulders",
    equipment: "Dumbbell",
  },
  {
    base: "Leg Press",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Quads",
    equipment: "Machine",
  },
  {
    base: "Hip Thrust",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Banded"],
    muscle: "Glutes",
    equipment: "Barbell",
  },
  {
    base: "Romanian Deadlift",
    prefixes: ["Paused", "Tempo", "Deficit"],
    muscle: "Hamstrings",
    equipment: "Barbell",
  },
  {
    base: "Front Squat",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Pin"],
    muscle: "Quads",
    equipment: "Barbell",
  },
  {
    base: "Incline Bench Press",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Banded", "Chained"],
    muscle: "Chest",
    equipment: "Barbell",
  },
  {
    base: "Incline Dumbbell Press",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Eccentric"],
    muscle: "Chest",
    equipment: "Dumbbell",
  },
  {
    base: "Dumbbell Row",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Eccentric", "Drop-Set"],
    muscle: "Back",
    equipment: "Dumbbell",
  },
  {
    base: "Cable Row",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Back",
    equipment: "Cable",
  },
  {
    base: "Lat Pulldown",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set", "Eccentric"],
    muscle: "Lats",
    equipment: "Cable",
  },
  {
    base: "Hack Squat",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Quads",
    equipment: "Machine",
  },
  {
    base: "Goblet Squat",
    prefixes: ["Paused", "Tempo", "1.5-Rep"],
    muscle: "Quads",
    equipment: "Dumbbell",
  },
  {
    base: "Bulgarian Split Squat",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Eccentric"],
    muscle: "Quads",
    equipment: "Dumbbell",
  },
  {
    base: "Leg Curl",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set", "Eccentric"],
    muscle: "Hamstrings",
    equipment: "Machine",
  },
  {
    base: "Leg Extension",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Quads",
    equipment: "Machine",
  },
  {
    base: "Calf Raise",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Calves",
    equipment: "Machine",
  },
  {
    base: "Pec Deck",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Chest",
    equipment: "Machine",
  },
  {
    base: "Cable Fly",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Chest",
    equipment: "Cable",
  },
  {
    base: "Cable Curl",
    prefixes: ["Paused", "Tempo", "21s", "Drop-Set"],
    muscle: "Biceps",
    equipment: "Cable",
  },
  {
    base: "Hammer Curl",
    prefixes: ["Paused", "Tempo", "21s", "Drop-Set"],
    muscle: "Biceps",
    equipment: "Dumbbell",
  },
  {
    base: "Preacher Curl",
    prefixes: ["Paused", "Tempo", "21s", "Drop-Set", "Eccentric"],
    muscle: "Biceps",
    equipment: "Machine",
  },
  {
    base: "Skull Crusher",
    prefixes: ["Paused", "Tempo", "Eccentric"],
    muscle: "Triceps",
    equipment: "EZ Bar",
  },
  {
    base: "Overhead Tricep Extension",
    prefixes: ["Paused", "Tempo", "Drop-Set"],
    muscle: "Triceps",
    equipment: "Cable",
  },
  {
    base: "Face Pull",
    prefixes: ["Paused", "Tempo", "21s", "Drop-Set"],
    muscle: "Shoulders",
    equipment: "Cable",
  },
  {
    base: "Reverse Pec Deck",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Shoulders",
    equipment: "Machine",
  },
  {
    base: "Barbell Curl",
    prefixes: ["Paused", "Tempo", "21s", "Drop-Set"],
    muscle: "Biceps",
    equipment: "Barbell",
  },
  {
    base: "Dumbbell Bench Press",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Eccentric", "Drop-Set"],
    muscle: "Chest",
    equipment: "Dumbbell",
  },
  {
    base: "Dumbbell Shoulder Press",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Eccentric", "Drop-Set"],
    muscle: "Shoulders",
    equipment: "Dumbbell",
  },
  {
    base: "Hip Abduction",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Glutes",
    equipment: "Machine",
  },
  {
    base: "Glute Kickback",
    prefixes: ["Paused", "Tempo", "1.5-Rep", "Drop-Set"],
    muscle: "Glutes",
    equipment: "Cable",
  },
  {
    base: "Cable Crunch",
    prefixes: ["Paused", "Tempo", "21s", "Drop-Set"],
    muscle: "Abs",
    equipment: "Cable",
  },
  {
    base: "Hanging Leg Raise",
    prefixes: ["Paused", "Tempo", "Eccentric"],
    muscle: "Abs",
    equipment: "Bodyweight",
  },
];

const expanded: Row[] = [...ROWS];
for (const v of VARIANT_AMPLIFIERS) {
  for (const p of v.prefixes) {
    expanded.push([`${p} ${v.base}`, v.muscle, v.equipment, "Strength"]);
  }
}

function slug(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Deduplicate by name
const seenIds = new Set<string>();
export const EXERCISES: Exercise[] = expanded
  .map(([name, muscle, equipment, category, isCompound]) => ({
    id: slug(name),
    name,
    muscle,
    equipment,
    category,
    isCompound: !!isCompound,
  }))
  .filter((e) => {
    if (seenIds.has(e.id)) return false;
    seenIds.add(e.id);
    return true;
  });

export const EXERCISE_BY_ID: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Abs",
  "Obliques",
  "Traps",
  "Lats",
  "Cardio",
  "Full Body",
];

export const EQUIPMENT: Equipment[] = [
  "Barbell",
  "Dumbbell",
  "Cable",
  "Machine",
  "Bodyweight",
  "Smith",
  "Kettlebell",
  "Band",
  "EZ Bar",
  "Trap Bar",
  "Other",
];
